/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *vbox3;
  GtkWidget *menu;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *load;
  GtkWidget *save;
  GtkWidget *build;
  GtkWidget *trennlinie2;
  GtkWidget *quit;
  GtkWidget *hbox1;
  GtkWidget *vbox4;
  GtkWidget *scrolledwindow2;
  GtkWidget *scenarios;
  GtkWidget *label18;
  GtkWidget *vbox5;
  GtkWidget *vbox6;
  GtkWidget *hbox2;
  GtkWidget *vbox7;
  GtkWidget *add_label;
  GtkWidget *hbox3;
  GtkWidget *vbox8;
  GtkWidget *players;
  GList *players_items = NULL;
  GtkWidget *players_entry;
  GtkWidget *classes;
  GList *classes_items = NULL;
  GtkWidget *classes_entry;
  GtkWidget *scrolledwindow4;
  GtkWidget *units;
  GtkWidget *label21;
  GtkWidget *scrolledwindow5;
  GtkWidget *transporters;
  GtkWidget *label22;
  GtkWidget *vbox9;
  GtkWidget *table1;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *exp;
  GList *exp_items = NULL;
  GtkWidget *exp_entry;
  GtkWidget *strength;
  GList *strength_items = NULL;
  GtkWidget *strength_entry;
  GtkObject *delay_adj;
  GtkWidget *delay;
  GtkWidget *add;
  GtkWidget *replace;
  GtkWidget *remove;
  GtkWidget *reinforcements;
  GtkWidget *label19;

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window), "window", window);
  gtk_window_set_title (GTK_WINDOW (window), "Reinforcements Editor");
  gtk_window_set_default_size (GTK_WINDOW (window), 400, 300);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window), vbox3);

  menu = gtk_menu_bar_new ();
  gtk_widget_ref (menu);
  gtk_object_set_data_full (GTK_OBJECT (window), "menu", menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menu);
  gtk_box_pack_start (GTK_BOX (vbox3), menu, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_label ("File");
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (window), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menu), file);

  file_menu = gtk_menu_new ();
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (window), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  load = gtk_menu_item_new_with_label ("Load");
  gtk_widget_ref (load);
  gtk_object_set_data_full (GTK_OBJECT (window), "load", load,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load);
  gtk_container_add (GTK_CONTAINER (file_menu), load);

  save = gtk_menu_item_new_with_label ("Save");
  gtk_widget_ref (save);
  gtk_object_set_data_full (GTK_OBJECT (window), "save", save,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save);
  gtk_container_add (GTK_CONTAINER (file_menu), save);

  build = gtk_menu_item_new_with_label ("Build");
  gtk_widget_ref (build);
  gtk_object_set_data_full (GTK_OBJECT (window), "build", build,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (build);
  gtk_container_add (GTK_CONTAINER (file_menu), build);

  trennlinie2 = gtk_menu_item_new ();
  gtk_widget_ref (trennlinie2);
  gtk_object_set_data_full (GTK_OBJECT (window), "trennlinie2", trennlinie2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (trennlinie2);
  gtk_container_add (GTK_CONTAINER (file_menu), trennlinie2);
  gtk_widget_set_sensitive (trennlinie2, FALSE);

  quit = gtk_menu_item_new_with_label ("Quit");
  gtk_widget_ref (quit);
  gtk_object_set_data_full (GTK_OBJECT (window), "quit", quit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (file_menu), quit);

  hbox1 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 4);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox4, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (window), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  scenarios = gtk_clist_new (1);
  gtk_widget_ref (scenarios);
  gtk_object_set_data_full (GTK_OBJECT (window), "scenarios", scenarios,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scenarios);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), scenarios);
  gtk_widget_set_usize (scenarios, 130, -2);
  gtk_container_set_border_width (GTK_CONTAINER (scenarios), 2);
  gtk_clist_set_column_width (GTK_CLIST (scenarios), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (scenarios));

  label18 = gtk_label_new ("Scenario");
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (window), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (scenarios), 0, label18);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox5, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox6, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (window), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox2, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox7, TRUE, TRUE, 0);

  add_label = gtk_label_new ("Add Unit For Poland");
  gtk_widget_ref (add_label);
  gtk_object_set_data_full (GTK_OBJECT (window), "add_label", add_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_label);
  gtk_box_pack_start (GTK_BOX (vbox7), add_label, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (window), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 2);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox8, TRUE, TRUE, 0);

  players = gtk_combo_new ();
  gtk_widget_ref (players);
  gtk_object_set_data_full (GTK_OBJECT (window), "players", players,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (players);
  gtk_box_pack_start (GTK_BOX (vbox8), players, FALSE, FALSE, 0);
  players_items = g_list_append (players_items, (gpointer) "Axis");
  players_items = g_list_append (players_items, (gpointer) "Allies");
  gtk_combo_set_popdown_strings (GTK_COMBO (players), players_items);
  g_list_free (players_items);

  players_entry = GTK_COMBO (players)->entry;
  gtk_widget_ref (players_entry);
  gtk_object_set_data_full (GTK_OBJECT (window), "players_entry", players_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (players_entry);
  gtk_entry_set_editable (GTK_ENTRY (players_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (players_entry), "Axis");

  classes = gtk_combo_new ();
  gtk_widget_ref (classes);
  gtk_object_set_data_full (GTK_OBJECT (window), "classes", classes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (classes);
  gtk_box_pack_start (GTK_BOX (vbox8), classes, FALSE, FALSE, 0);
  classes_items = g_list_append (classes_items, (gpointer) "Infantry");
  classes_items = g_list_append (classes_items, (gpointer) "Tank");
  classes_items = g_list_append (classes_items, (gpointer) "Recon");
  classes_items = g_list_append (classes_items, (gpointer) "Anti-Tank");
  classes_items = g_list_append (classes_items, (gpointer) "Artillery");
  classes_items = g_list_append (classes_items, (gpointer) "Anti-Aircraft");
  classes_items = g_list_append (classes_items, (gpointer) "Air-Defense");
  classes_items = g_list_append (classes_items, (gpointer) "Fighter");
  classes_items = g_list_append (classes_items, (gpointer) "Tactical Bomber");
  classes_items = g_list_append (classes_items, (gpointer) "Level Bomber");
  classes_items = g_list_append (classes_items, (gpointer) "Submarine");
  classes_items = g_list_append (classes_items, (gpointer) "Destroyer");
  classes_items = g_list_append (classes_items, (gpointer) "Capital Ship");
  classes_items = g_list_append (classes_items, (gpointer) "Aircraft Carrier");
  gtk_combo_set_popdown_strings (GTK_COMBO (classes), classes_items);
  g_list_free (classes_items);

  classes_entry = GTK_COMBO (classes)->entry;
  gtk_widget_ref (classes_entry);
  gtk_object_set_data_full (GTK_OBJECT (window), "classes_entry", classes_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (classes_entry);
  gtk_entry_set_editable (GTK_ENTRY (classes_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (classes_entry), "Infantry");

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (window), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  units = gtk_clist_new (1);
  gtk_widget_ref (units);
  gtk_object_set_data_full (GTK_OBJECT (window), "units", units,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (units);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), units);
  gtk_widget_set_usize (units, 140, 160);
  gtk_container_set_border_width (GTK_CONTAINER (units), 2);
  gtk_clist_set_column_width (GTK_CLIST (units), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (units));

  label21 = gtk_label_new ("Unit");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (window), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_clist_set_column_widget (GTK_CLIST (units), 0, label21);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (window), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  transporters = gtk_clist_new (1);
  gtk_widget_ref (transporters);
  gtk_object_set_data_full (GTK_OBJECT (window), "transporters", transporters,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (transporters);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), transporters);
  gtk_widget_set_usize (transporters, 140, 130);
  gtk_container_set_border_width (GTK_CONTAINER (transporters), 2);
  gtk_clist_set_column_width (GTK_CLIST (transporters), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (transporters));

  label22 = gtk_label_new ("Transporter");
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (window), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_clist_set_column_widget (GTK_CLIST (transporters), 0, label22);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (window), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox9, TRUE, TRUE, 0);

  table1 = gtk_table_new (3, 2, TRUE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (window), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox9), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  label23 = gtk_label_new ("Delay:");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (window), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table1), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new ("Strength:");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (window), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table1), label24, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new ("Experience:");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (window), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table1), label25, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  exp = gtk_combo_new ();
  gtk_widget_ref (exp);
  gtk_object_set_data_full (GTK_OBJECT (window), "exp", exp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exp);
  gtk_table_attach (GTK_TABLE (table1), exp, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  exp_items = g_list_append (exp_items, (gpointer) "0");
  exp_items = g_list_append (exp_items, (gpointer) "1");
  exp_items = g_list_append (exp_items, (gpointer) "2");
  exp_items = g_list_append (exp_items, (gpointer) "3");
  exp_items = g_list_append (exp_items, (gpointer) "4");
  exp_items = g_list_append (exp_items, (gpointer) "5");
  gtk_combo_set_popdown_strings (GTK_COMBO (exp), exp_items);
  g_list_free (exp_items);

  exp_entry = GTK_COMBO (exp)->entry;
  gtk_widget_ref (exp_entry);
  gtk_object_set_data_full (GTK_OBJECT (window), "exp_entry", exp_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exp_entry);
  gtk_entry_set_editable (GTK_ENTRY (exp_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (exp_entry), "0");

  strength = gtk_combo_new ();
  gtk_widget_ref (strength);
  gtk_object_set_data_full (GTK_OBJECT (window), "strength", strength,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (strength);
  gtk_table_attach (GTK_TABLE (table1), strength, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  strength_items = g_list_append (strength_items, (gpointer) "5");
  strength_items = g_list_append (strength_items, (gpointer) "8");
  strength_items = g_list_append (strength_items, (gpointer) "10");
  strength_items = g_list_append (strength_items, (gpointer) "12");
  strength_items = g_list_append (strength_items, (gpointer) "15");
  gtk_combo_set_popdown_strings (GTK_COMBO (strength), strength_items);
  g_list_free (strength_items);

  strength_entry = GTK_COMBO (strength)->entry;
  gtk_widget_ref (strength_entry);
  gtk_object_set_data_full (GTK_OBJECT (window), "strength_entry", strength_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (strength_entry);
  gtk_entry_set_text (GTK_ENTRY (strength_entry), "10");

  delay_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  delay = gtk_spin_button_new (GTK_ADJUSTMENT (delay_adj), 1, 0);
  gtk_widget_ref (delay);
  gtk_object_set_data_full (GTK_OBJECT (window), "delay", delay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delay);
  gtk_table_attach (GTK_TABLE (table1), delay, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (delay), TRUE);

  add = gtk_button_new_with_label ("Add Unit");
  gtk_widget_ref (add);
  gtk_object_set_data_full (GTK_OBJECT (window), "add", add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add);
  gtk_box_pack_start (GTK_BOX (vbox9), add, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (add), 5);

  replace = gtk_button_new_with_label ("ReplaceUnit");
  gtk_widget_ref (replace);
  gtk_object_set_data_full (GTK_OBJECT (window), "replace", replace,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (replace);
  gtk_box_pack_start (GTK_BOX (vbox9), replace, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (replace), 5);

  remove = gtk_button_new_with_label ("Remove Unit");
  gtk_widget_ref (remove);
  gtk_object_set_data_full (GTK_OBJECT (window), "remove", remove,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (remove);
  gtk_box_pack_start (GTK_BOX (vbox9), remove, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (remove), 5);

  reinforcements = gtk_clist_new (1);
  gtk_widget_ref (reinforcements);
  gtk_object_set_data_full (GTK_OBJECT (window), "reinforcements", reinforcements,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reinforcements);
  gtk_box_pack_start (GTK_BOX (vbox9), reinforcements, TRUE, TRUE, 0);
  gtk_widget_set_usize (reinforcements, -2, 150);
  gtk_clist_set_column_width (GTK_CLIST (reinforcements), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (reinforcements));

  label19 = gtk_label_new ("Reinforcements");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (window), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (reinforcements), 0, label19);

  gtk_signal_connect (GTK_OBJECT (window), "destroy",
                      GTK_SIGNAL_FUNC (on_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file), "activate",
                      GTK_SIGNAL_FUNC (on_file_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load), "activate",
                      GTK_SIGNAL_FUNC (on_load_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save), "activate",
                      GTK_SIGNAL_FUNC (on_save_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (build), "activate",
                      GTK_SIGNAL_FUNC (on_build_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit), "activate",
                      GTK_SIGNAL_FUNC (on_quit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (scenarios), "select_row",
                      GTK_SIGNAL_FUNC (on_scenarios_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (players_entry), "changed",
                      GTK_SIGNAL_FUNC (on_players_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (classes_entry), "changed",
                      GTK_SIGNAL_FUNC (on_classes_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (units), "select_row",
                      GTK_SIGNAL_FUNC (on_units_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (transporters), "select_row",
                      GTK_SIGNAL_FUNC (on_transporters_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (add), "clicked",
                      GTK_SIGNAL_FUNC (on_add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (replace), "clicked",
                      GTK_SIGNAL_FUNC (on_replace_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (remove), "clicked",
                      GTK_SIGNAL_FUNC (on_remove_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reinforcements), "select_row",
                      GTK_SIGNAL_FUNC (on_reinforcements_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reinforcements), "key_press_event",
                      GTK_SIGNAL_FUNC (on_reinforcements_key_press_event),
                      NULL);

  return window;
}

