.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LGENERAL 6 "November 13, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
LGeneral \- a turn-based strategy game engine. 
.SH SYNOPSIS
.B lgeneral

.SH DESCRIPTION
LGeneral is a strategy game engine similar to SSI's Panzer General\*R,
but it has some differences to the original:
.TP
1)Reinforcement: 
.TP
In Panzer General\*R you could buy reinforcement by prestige. In LGeneral reinforcement appears in a specific turn and will be 		placed around an allied town that was not lost during playing. This also means that conquered towns may not serve as deploy centers.
.TP
.TP
2)Core Units:
.TP
You do not have core units in LGeneral. 
.TP

.SH OPTIONS
This program has no command line opotions.
.TP

.SH AUTHOR
.TP
This manual page was written by Gernot Galli <gernot_galli@onlinehome.de>,
for the Debian GNU/Linux system (but may be used by others).
